@extends('admin.layouts.app')

@section('title', 'Chapters')

@push('styles')
<style>
.ch-page{display:grid;grid-template-columns:minmax(280px,1fr) minmax(0,2fr);gap:8px}.ch-box{overflow:hidden;border:1px solid #cfcfcf;border-radius:6px;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.08)}.ch-title{border-bottom:1px solid #d5d5d5;padding:8px 10px;color:#1f2937;font-size:18px}.ch-form,.ch-list{padding:10px}.ch-field{margin-bottom:13px}.ch-form label{display:block;margin-bottom:5px;color:#1f2937;font-size:14px}.ch-req{color:#e11d48}.ch-input,.ch-select{width:100%;border:1px solid #bdbdbd;border-radius:3px;padding:8px;font-size:14px;background:#fff}.ch-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ch-more{display:flex;justify-content:flex-end;margin:3px 0 10px}.ch-btn{border:0;border-radius:2px;background:#24448d;padding:7px 14px;color:#fff;cursor:pointer;font-size:14px;text-decoration:none}.ch-btn:hover{background:#2f61b3}.ch-add{padding:3px 6px;font-size:12px}.ch-remove{border:0;background:transparent;color:#dc3545;cursor:pointer;font-size:16px}.ch-footer{display:flex;justify-content:flex-end;margin:10px -10px -10px;border-top:1px solid #d5d5d5;padding:10px}.ch-tools{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.ch-search{width:175px;border:1px solid #999;border-radius:4px;padding:5px}.ch-exports{display:flex;gap:4px}.ch-exports button{width:27px;height:27px;border:0;border-radius:4px;background:#24448d;color:#fff;cursor:pointer}.ch-exports button:hover{background:#3f70c9}.ch-table-wrap{overflow-x:auto}.ch-table{width:100%;border-collapse:collapse;font-size:13px}.ch-table th{background:#24448d;padding:9px 8px;color:#fff;text-align:left;font-weight:700;font-size:14px}.ch-table td{border-bottom:1px solid #e5e7eb;padding:8px;vertical-align:top}.ch-table tbody tr:hover{background:#f4f7fb}.ch-subject{margin:-8px;padding:8px;background:#e8e8e8;font-weight:700}.ch-detail{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;padding:7px 0}.ch-action{display:inline-flex;width:26px;height:26px;align-items:center;justify-content:center;border:0;border-radius:3px;color:#fff;text-decoration:none;cursor:pointer}.ch-edit{background:#24448d}.ch-delete{background:#dc3545}.ch-empty{padding:55px 10px;color:#f29ca4;text-align:center}.ch-foot{display:flex;justify-content:space-between;padding-top:8px;color:#666;font-size:12px}.ch-error{color:#dc2626;font-size:12px;margin-top:3px}.ch-row-extra{display:grid;grid-template-columns:1fr 1fr 22px;gap:8px;margin-top:8px}.ch-remove-row{padding-top:25px}@media(max-width:900px){.ch-page{grid-template-columns:1fr}}@media print{.admin-sidebar,.admin-topbar,.admin-module-tabs,.ch-form-box,.ch-tools,.ch-action-col,.ch-foot,.admin-footer{display:none!important}.admin-content-wrap{padding-left:0!important}.admin-main{padding:0!important}}
</style>
@endpush

@section('content')
<div class="ch-page">
    <section class="ch-box ch-form-box">
        <h2 class="ch-title">{{ $chapter ? 'Edit Chapter' : 'Add Chapter' }}</h2>
        <form class="ch-form" method="POST" action="{{ $chapter ? route('admin.academics.chapters.update',$chapter,absolute:false) : route('admin.academics.chapters.store',absolute:false) }}">
            @csrf @if($chapter) @method('PUT') @endif
            <div class="ch-field"><label>Class <span class="ch-req">*</span></label><select id="chapter-class" name="class_id" class="ch-select" required><option value="">Select</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected((string)old('class_id',$selectedClass)===(string)$class->id)>{{ $class->class }}</option>@endforeach</select>@error('class_id')<p class="ch-error">{{ $message }}</p>@enderror</div>
            <div class="ch-field"><label>Subject <span class="ch-req">*</span></label><select id="chapter-subject" name="subject_id" class="ch-select" required><option value="">Select</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected((string)old('subject_id',$chapter?->subject_id)===(string)$subject->id)>{{ $subject->name }}@if($subject->code) ({{ $subject->code }})@endif</option>@endforeach</select>@error('subject_id')<p class="ch-error">{{ $message }}</p>@enderror</div>
            <div id="chapter-rows">
                @php($englishNames=old('eng_name',$chapter ? [$chapter->name] : [''])) @php($urduNames=old('urdu_name',$chapter ? [$chapter->urdu] : ['']))
                @foreach($englishNames as $index=>$english)
                    <div class="ch-row chapter-row"><div><label>Name English <span class="ch-req">*</span></label><input name="eng_name[]" class="ch-input" value="{{ $english }}" required></div><div><label>Name Urdu</label><input name="urdu_name[]" class="ch-input" value="{{ $urduNames[$index] ?? '' }}"></div>@if($index>0)<div class="ch-remove-row"><button type="button" class="ch-remove-row-btn ch-remove-row">×</button></div>@endif</div>
                @endforeach
            </div>
            @error('eng_name')<p class="ch-error">{{ $message }}</p>@enderror @error('eng_name.*')<p class="ch-error">{{ $message }}</p>@enderror
            @unless($chapter)<div class="ch-more"><button type="button" id="add-chapter-row" class="ch-btn ch-add"><i class="fa-solid fa-plus"></i> Add More...</button></div>@endunless
            <div class="ch-footer">@if($chapter)<a class="ch-btn mr-2 bg-neutral-500" href="{{ route('admin.academics.chapters.index',absolute:false) }}">Cancel</a>@endif<button class="ch-btn" type="submit">{{ $chapter?'Update':'Save' }}</button></div>
        </form>
    </section>

    <section class="ch-box"><h2 class="ch-title">Chapter List</h2><div class="ch-list">
        <div class="ch-tools"><form method="GET" action="{{ route('admin.academics.chapters.index',absolute:false) }}"><input class="ch-search" name="search" value="{{ request('search') }}" placeholder="Search..."></form><div class="ch-exports"><button type="button" data-ch-export="copy" title="Copy"><i class="fa-regular fa-copy"></i></button><button type="button" data-ch-export="excel" title="Excel"><i class="fa-regular fa-file-excel"></i></button><button type="button" data-ch-export="csv" title="CSV"><i class="fa-regular fa-file-lines"></i></button><button type="button" data-ch-export="pdf" title="PDF"><i class="fa-regular fa-file-pdf"></i></button><button type="button" data-ch-export="print" title="Print"><i class="fa-solid fa-print"></i></button></div></div>
        <div class="ch-table-wrap"><table id="chapter-table" class="ch-table"><thead><tr><th>Class ▼</th><th>Subject / Chapter</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ $classNames[$record->class_id] ?? $record->class_id }}</td><td><div class="ch-subject">{{ $record->subject?->name ?? 'Subject' }}</div><div class="ch-detail"><span>{{ $record->name }}</span><span dir="rtl">{{ $record->urdu }}</span><span class="ch-action-col"><a class="ch-action ch-edit" href="{{ route('admin.academics.chapters.index',['edit'=>$record->id],absolute:false) }}" title="Edit"><i class="fa-solid fa-pencil"></i></a> <form class="inline" method="POST" action="{{ route('admin.academics.chapters.destroy',$record,absolute:false) }}" onsubmit="return confirm('Delete this chapter?')">@csrf @method('DELETE')<button class="ch-action ch-delete" title="Delete"><i class="fa-solid fa-trash"></i></button></form></span></div></td></tr>@empty<tr><td colspan="2" class="ch-empty">No data available in table</td></tr>@endforelse</tbody></table></div>
        <div class="ch-foot"><span>Records: {{ $records->total() ? (($records->currentPage()-1)*$records->perPage()+1):0 }} to {{ ($records->currentPage()-1)*$records->perPage()+$records->count() }} of {{ $records->total() }}</span><span>{{ $records->links() }}</span></div>
    </div></section>
</div>
@endsection

@push('scripts')
<script>
(() => { const classSelect=document.getElementById('chapter-class'), subjectSelect=document.getElementById('chapter-subject'); classSelect?.addEventListener('change',()=>{const url=new URL(window.location.href);url.search='';url.searchParams.set('class_id',classSelect.value);window.location.href=url.toString()}); document.getElementById('add-chapter-row')?.addEventListener('click',()=>{const row=document.createElement('div');row.className='ch-row-extra chapter-row';row.innerHTML='<div><label>Name English <span class="ch-req">*</span></label><input name="eng_name[]" class="ch-input" required></div><div><label>Name Urdu</label><input name="urdu_name[]" class="ch-input"></div><div class="ch-remove-row"><button type="button" class="ch-remove-row-btn ch-remove">×</button></div>';document.getElementById('chapter-rows').append(row)}); document.getElementById('chapter-rows')?.addEventListener('click',e=>{if(e.target.closest('.ch-remove-row-btn'))e.target.closest('.chapter-row').remove()}); const table=document.getElementById('chapter-table');const rows=[...table.querySelectorAll('tbody tr')].filter(r=>r.children.length===2);const data=()=>rows.map(r=>[...r.children].map(c=>c.innerText.trim()));const download=(c,n,t)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click();URL.revokeObjectURL(a.href)};const csv=()=>[['Class','Subject / Chapter'],...data().map(r=>r.slice(0,2))].map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');document.querySelectorAll('[data-ch-export]').forEach(b=>b.addEventListener('click',async()=>{const t=b.dataset.chExport;if(t==='copy')await navigator.clipboard.writeText(data().map(r=>r.slice(0,2).join('\t')).join('\n'));if(t==='csv')download(csv(),'chapters.csv','text/csv');if(t==='excel')download(`<table>${table.innerHTML}</table>`,'chapters.xls','application/vnd.ms-excel');if(t==='pdf'||t==='print')window.print()})); })();
</script>
@endpush
