@extends('admin.layouts.app')

@section('title', 'Topics')

@push('styles')
<style>
.tp-page{display:grid;grid-template-columns:minmax(280px,1fr) minmax(0,2fr);gap:8px}.tp-box{overflow:hidden;border:1px solid #cfcfcf;border-radius:6px;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.08)}.tp-title{border-bottom:1px solid #d5d5d5;padding:8px 10px;color:#1f2937;font-size:18px}.tp-form,.tp-list{padding:10px}.tp-field{margin-bottom:13px}.tp-form label{display:block;margin-bottom:5px;color:#1f2937;font-size:14px}.tp-req{color:#e11d48}.tp-input,.tp-select{width:100%;border:1px solid #bdbdbd;border-radius:3px;padding:8px;font-size:14px;background:#fff}.tp-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tp-more{display:flex;justify-content:flex-end;margin:3px 0 10px}.tp-btn{border:0;border-radius:2px;background:#24448d;padding:7px 14px;color:#fff;cursor:pointer;font-size:14px;text-decoration:none}.tp-btn:hover{background:#2f61b3}.tp-add{padding:3px 6px;font-size:12px}.tp-remove{border:0;background:transparent;color:#dc3545;cursor:pointer;font-size:16px}.tp-footer{display:flex;justify-content:flex-end;margin:10px -10px -10px;border-top:1px solid #d5d5d5;padding:10px}.tp-tools{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.tp-search{width:175px;border:1px solid #999;border-radius:4px;padding:5px}.tp-exports{display:flex;gap:4px}.tp-exports button{width:27px;height:27px;border:0;border-radius:4px;background:#24448d;color:#fff;cursor:pointer}.tp-exports button:hover{background:#3f70c9}.tp-table-wrap{overflow-x:auto}.tp-table{width:100%;border-collapse:collapse;font-size:13px}.tp-table th{background:#24448d;padding:9px 8px;color:#fff;text-align:left;font-weight:700;font-size:14px}.tp-table td{border-bottom:1px solid #e5e7eb;padding:8px;vertical-align:top}.tp-table tbody tr:hover{background:#f4f7fb}.tp-subject{margin:-8px;padding:8px;background:#e8e8e8;font-weight:700}.tp-chapter{padding:6px 0;font-weight:700}.tp-detail{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;padding:6px 0 2px 24px;font-weight:400}.tp-action{display:inline-flex;width:26px;height:26px;align-items:center;justify-content:center;border:0;border-radius:3px;color:#fff;text-decoration:none;cursor:pointer}.tp-edit{background:#24448d}.tp-delete{background:#dc3545}.tp-empty{padding:55px 10px;color:#f29ca4;text-align:center}.tp-foot{display:flex;justify-content:space-between;padding-top:8px;color:#666;font-size:12px}.tp-error{color:#dc2626;font-size:12px;margin-top:3px}@media(max-width:900px){.tp-page{grid-template-columns:1fr}}@media print{.admin-sidebar,.admin-topbar,.admin-module-tabs,.tp-form-box,.tp-tools,.tp-action-col,.tp-foot,.admin-footer{display:none!important}.admin-content-wrap{padding-left:0!important}.admin-main{padding:0!important}}
</style>
@endpush

@section('content')
<div class="tp-page">
    <section class="tp-box tp-form-box"><h2 class="tp-title">{{ $topic?'Edit Topic':'Add Topic' }}</h2>
        <form class="tp-form" method="POST" action="{{ $topic?route('admin.academics.topics.update',$topic,absolute:false):route('admin.academics.topics.store',absolute:false) }}">
            @csrf @if($topic) @method('PUT') @endif
            <div class="tp-field"><label>Class</label><select id="topic-class" name="class_id" class="tp-select" required><option value="">Select</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected((string)old('class_id',$selectedClass)===(string)$class->id)>{{ $class->class }}</option>@endforeach</select>@error('class_id')<p class="tp-error">{{ $message }}</p>@enderror</div>
            <div class="tp-field"><label>Subject</label><select id="topic-subject" name="subject_id" class="tp-select" required><option value="">Select</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected((string)old('subject_id',$selectedSubject)===(string)$subject->id)>{{ $subject->name }}@if($subject->code) ({{ $subject->code }})@endif</option>@endforeach</select>@error('subject_id')<p class="tp-error">{{ $message }}</p>@enderror</div>
            <div class="tp-field"><label>Chapter</label><select id="topic-chapter" name="chapter_id" class="tp-select" required><option value="">Select</option>@foreach($chapters as $chapterOption)<option value="{{ $chapterOption->id }}" @selected((string)old('chapter_id',$topic?->chapter_id)===(string)$chapterOption->id)>{{ $chapterOption->name }} @if($chapterOption->urdu) {{ $chapterOption->urdu }} @endif</option>@endforeach</select>@error('chapter_id')<p class="tp-error">{{ $message }}</p>@enderror</div>
            <div id="topic-rows">@php($englishNames=old('eng_name',$topic ? [$topic->name] : [''])) @php($urduNames=old('urdu_name',$topic ? [$topic->urdu] : [''])) @foreach($englishNames as $index=>$english)<div class="tp-row topic-row"><div><label>Name English <span class="tp-req">*</span></label><input name="eng_name[]" class="tp-input" value="{{ $english }}" required></div><div><label>Name Urdu</label><input name="urdu_name[]" class="tp-input" value="{{ $urduNames[$index]??'' }}"></div>@if($index>0)<div><button type="button" class="tp-remove topic-remove">×</button></div>@endif</div>@endforeach</div>
            @error('eng_name')<p class="tp-error">{{ $message }}</p>@enderror @error('eng_name.*')<p class="tp-error">{{ $message }}</p>@enderror
            @unless($topic)<div class="tp-more"><button type="button" id="add-topic-row" class="tp-btn tp-add"><i class="fa-solid fa-plus"></i> Add More...</button></div>@endunless
            <div class="tp-footer">@if($topic)<a class="tp-btn mr-2 bg-neutral-500" href="{{ route('admin.academics.topics.index',absolute:false) }}">Cancel</a>@endif<button class="tp-btn" type="submit">{{ $topic?'Update':'Save' }}</button></div>
        </form>
    </section>

    <section class="tp-box"><h2 class="tp-title">Topic List</h2><div class="tp-list"><div class="tp-tools"><form method="GET" action="{{ route('admin.academics.topics.index',absolute:false) }}"><input class="tp-search" name="search" value="{{ request('search') }}" placeholder="Search..."></form><div class="tp-exports"><button type="button" data-tp-export="copy" title="Copy"><i class="fa-regular fa-copy"></i></button><button type="button" data-tp-export="excel" title="Excel"><i class="fa-regular fa-file-excel"></i></button><button type="button" data-tp-export="csv" title="CSV"><i class="fa-regular fa-file-lines"></i></button><button type="button" data-tp-export="pdf" title="PDF"><i class="fa-regular fa-file-pdf"></i></button><button type="button" data-tp-export="print" title="Print"><i class="fa-solid fa-print"></i></button></div></div>
        <div class="tp-table-wrap"><table id="topic-table" class="tp-table"><thead><tr><th>Class ▼</th><th>Subject / Chapter / Topic</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ $classNames[$record->class_id]??$record->class_id }}</td><td><div class="tp-subject">{{ $record->chapter?->subject?->name??'Subject' }}</div><div class="tp-chapter">{{ $record->chapter?->name??'Chapter' }} @if($record->chapter?->urdu) {{ $record->chapter->urdu }} @endif</div><div class="tp-detail"><span>{{ $record->name }}</span><span dir="rtl">{{ $record->urdu }}</span><span class="tp-action-col"><a class="tp-action tp-edit" href="{{ route('admin.academics.topics.index',['edit'=>$record->id],absolute:false) }}" title="Edit"><i class="fa-solid fa-pencil"></i></a> <form class="inline" method="POST" action="{{ route('admin.academics.topics.destroy',$record,absolute:false) }}" onsubmit="return confirm('Delete this topic?')">@csrf @method('DELETE')<button class="tp-action tp-delete" title="Delete"><i class="fa-solid fa-trash"></i></button></form></span></div></td></tr>@empty<tr><td colspan="2" class="tp-empty">No data available in table</td></tr>@endforelse</tbody></table></div><div class="tp-foot"><span>Records: {{ $records->total()?(($records->currentPage()-1)*$records->perPage()+1):0 }} to {{ ($records->currentPage()-1)*$records->perPage()+$records->count() }} of {{ $records->total() }}</span><span>{{ $records->links() }}</span></div>
    </div></section>
</div>
@endsection

@push('scripts')
<script>
(() => {const classSelect=document.getElementById('topic-class'),subjectSelect=document.getElementById('topic-subject');const reload=(classId,subjectId='')=>{const u=new URL(window.location.href);u.search='';if(classId)u.searchParams.set('class_id',classId);if(subjectId)u.searchParams.set('subject_id',subjectId);window.location.href=u.toString()};classSelect?.addEventListener('change',()=>reload(classSelect.value));subjectSelect?.addEventListener('change',()=>reload(classSelect.value,subjectSelect.value));document.getElementById('add-topic-row')?.addEventListener('click',()=>{const r=document.createElement('div');r.className='tp-row topic-row';r.innerHTML='<div><label>Name English <span class="tp-req">*</span></label><input name="eng_name[]" class="tp-input" required></div><div><label>Name Urdu</label><input name="urdu_name[]" class="tp-input"></div><div><button type="button" class="tp-remove topic-remove">×</button></div>';document.getElementById('topic-rows').append(r)});document.getElementById('topic-rows')?.addEventListener('click',e=>{if(e.target.closest('.topic-remove'))e.target.closest('.topic-row').remove()});const t=document.getElementById('topic-table'),rows=[...t.querySelectorAll('tbody tr')].filter(r=>r.children.length===2),data=()=>rows.map(r=>[...r.children].map(c=>c.innerText.trim())),download=(c,n,type)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type}));a.download=n;a.click();URL.revokeObjectURL(a.href)},csv=()=>[['Class','Subject / Chapter / Topic'],...data()].map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');document.querySelectorAll('[data-tp-export]').forEach(b=>b.addEventListener('click',async()=>{const x=b.dataset.tpExport;if(x==='copy')await navigator.clipboard.writeText(data().map(r=>r.join('\t')).join('\n'));if(x==='csv')download(csv(),'topics.csv','text/csv');if(x==='excel')download(`<table>${t.innerHTML}</table>`,'topics.xls','application/vnd.ms-excel');if(x==='pdf'||x==='print')window.print()}));})();
</script>
@endpush
